#!/bin/sh 
# Localize these. 
INSPECT_DIR=/var/spool/filter
#SENDMAIL=/usr/sbin/sendmail
SENDMAIL=/usr/sbin/sendmail.postfix
# Exit codes from <sysexits.h> 
EX_TEMPFAIL=75 
EX_UNAVAILABLE=69 
# Clean up when done or when aborting. 
trap "rm -f in.$$" 0 1 2 3 15 
# Start processing. 
cd $INSPECT_DIR || { echo $INSPECT_DIR does not exist; exit
$EX_TEMPFAIL; }
cat >in.$$ || { echo Cannot save mail to file; exit $EX_TEMPFAIL; } 
/usr/bin/altermime --input=in.$$ \
                  --disclaimer=/etc/postfix-fex/disclaimer.txt \
                  --disclaimer-html=/etc/postfix-fex/disclaimer.txt \
                  --xheader="X-Copyrighted-Material:" || \
                  { echo Message content rejected from disclmr filter; exit $EX_UNAVAILABLE; } 
$SENDMAIL "$@" <in.$$ 
exit $?
